function result = importfile(filename)

% IMPORTFILE Import data from a text file

%  IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DECANEPULSES180HZ1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Decanepulses180Hz1 = importfile("D:\Levitator\Decane pulses 180Hz.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Nov-2022 14:03:27

%% Input handling

% If dataLines is not specified, define defaults
% if nargin < 2
% 	dataLines = [2, Inf];
% end

%% Setup the Import Options


opts = detectImportOptions(filename);

% opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
% opts.DataLines = dataLines;
% opts.Delimiter = ",";

% Specify column names and types
% opts.VariableNames = ["VarName1", "Area", "X", "Y", "XM", "YM", "Perim", "BX", "BY", "Width", "Height", "Major", "Minor", "Angle", "Circ", "Feret", "Area1", "Slice", "FeretX", "FeretY", "FeretAngle", "MinFeret", "AR", "Round", "Solidity"];
% opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
% opts.ExtraColumnsRule = "ignore";
% opts.EmptyLineRule = "read";

% Import the data
result = readtable(filename, opts);

end